### ISSUE TITLE
c4 is not as popular as 4chan x

### ISSUE THREAD

**Issue by aeosynth** [qqueue/c4#9]
if you care at all, you could start bridging the gap by _hosting builds_, outlining differences, and treating chrome as a first class citizen (firefox is the only browser mentioned by name in the readme)

TODO:
- [x] host builds
  - subtask: let greasemonkey autoupdate
- [ ] outline differences
- [ ] support chrome
- [ ] get more users than 4chan X

**Comment by vendethiel** [comment]
The script [doesn't even run on chrome](https://github.com/qqueue/c4/pull/6#issuecomment-15088456). (and I'm too lazy to PR for that)

**Comment by saxamaphone69** [comment]
I'm not smart enough to 'build' this, but I would definitely be willing to use c4 if it were readily available. I liked the userscript when I first saw you post it on /g/, and I've been trying to follow along with commits since then with my limited understanding of the languages your using and it looks like this is still way cool.

**Comment by aeosynth** [comment]
https://plus.google.com/112678702228711889851/posts/eVeouesvaVX

> When software -- or idea-ware for that matter -- fails to be accessible to _anyone_ for _any reason_, it is the fault of the software or of the messaging of the idea.

**Comment by vendethiel** [comment]
@saxamaphone69 here : https://gist.github.com/Nami-Doc/b2c380a5044f49a48591

**Comment by aeosynth** [comment]
you guys should use the new `--no-node` flag that i requested - https://github.com/michaelficarra/commonjs-everywhere/issues/36

**Comment by vendethiel** [comment]
that's, like, 10 lines ? not sure that deserves an option. Plus I have sugar.js included in my shit, cause yolo

**Comment by vendethiel** [comment]
also won't update

XMLHttpRequest cannot load http://api.4chan.org/a/res/83573507.json. Origin chrome-extension://hbfhbfjecfkilkefimhcnljffjfffdld is not allowed by Access-Control-Allow-Origin.

**Comment by saxamaphone69** [comment]
@Nami-Doc Thanks!

**Comment by vendethiel** [comment]
@qqueue, wherefore art thou ? ríce behóf unc !

**Comment by qqueue** [comment]
Sorry, saxamaphone69 and anybody else who's interested. I know i'm being elitist by requiring compilation, and that it should be easier to install and test. Right now I'm just afraid that people will install c4, find out it's buggy and incomplete, and forever associate the name with the state of the project that they tried. Once I feel better about it (beta), easier installation/documentation will be more of a priority. Thank you for your interest despite that, please don't leave!

> treating chrome as a first class citizen

I got tired of dealing with issues on a browser I personally don't use, especially during alpha development, which is why the readme only mentions firefox. Patches and bug reports are always welcome, however (thanks nami-doc).

> hosting builds

I don't want to host through `blob/master` like 4chan-X used to do, since that messes up diffs and github stats.

The easiest alternative I can think of is to make a deploy script that pushes the compilied js to the orphan `gh-pages` branch so I can serve it from there. It'd still slightly bloat the repository, but it wouldn't bloat diffs on `master` at least.

> `--no-node`

Well, I already proverbially screwed the bloat pooch with `require \baconjs`, but I'll do it for kicks and a possible last-minute commit 'o' the day.

> Origin chrome-extension://hbfhbfjecfkilkefimhcnljffjfffdld is not allowed by Access-Control-Allow-Origin.

Well shit. I know that I had a solution to this last year, but I forget how or why it worked. Does anyone else know?

**Comment by aeosynth** [comment]
the [initial commit](https://github.com/qqueue/c4/commit/04a03f4ffb1d595aad0a60b0b84838654912a916) was a year ago; what's the roadmap to beta? software is usually never ``complete'', that shouldn't stop you from releasing

you can break the 4chan x monoculture

**Comment by qqueue** [comment]
https://github.com/qqueue/c4/wiki/TODO is basically correct, if a little vague. I'm aiming for enough differentiation to draw people from 4cx/vanilla despite a smaller absolute number of features, yet with enough stability for them to stick around, and for me to be able to fix bugs in a timely fashion.

Time-wise, I'm bogged down with college finals for the next few weeks, so June at the earliest.

**Comment by vendethiel** [comment]
> I don't want to host through blob/master like 4chan-X used to do, since that messes up diffs and github stats.

Just add a leading generated by

**Comment by qqueue** [comment]
> Just add a leading generated by

The 'generated by' thing is lame. Github should just support `.gitattributes` instead.

---

I fixed all the obvious bugs in master, and manually pushed a compiled version to `gh-pages`

http://qqueue.github.io/c4/c4.user.js

Try it out if you want.

**Comment by vendethiel** [comment]
answering now that I'm a bit more awake

> The 'generated by' thing is lame. Github should just support .gitattributes instead.

May be "lame" but I'd say that's the best

**Comment by vendethiel** [comment]
> Well shit. I know that I had a solution to this last year, but I forget how or why it worked. Does anyone else know?

found that http://stackoverflow.com/questions/6035179/google-chrome-extension-error-access-control-allow-origin ?

**Comment by qqueue** [comment]
I thought there was a way to make chrome cross-origin requests in converted userscripts, i.e. without the manifest. Maybe it's the implicit `//` protocol that's breaking?

**Comment by qqueue** [comment]
I updated the [README](https://github.com/qqueue/c4/blob/master/README.md) to be less recondite. Feedback welcome.

**Comment by nstepien** [comment]
Any progress on this?

**Comment by vendethiel** [comment]
outside of @qqueue 's death and then https://github.com/qqueue/c4/releases/tag/v0.1 ?

**Comment by nstepien** [comment]
Am interested in someone making something better than 4chan X, imagine all the free time I would have then!

**Comment by aeosynth** [comment]
you could bless a fork; that worked out for me

**Comment by nstepien** [comment]
There is still a substantial number of things I want to do though, and I don't believe anyone is willing to/capable of delivering work of quality.

**Comment by aeosynth** [comment]
how would "someone making something better than 4chan X" give you free time if "[t]here is still a substantial number of things [you] want to do"?

fuck i can't stop arguing

**Comment by nstepien** [comment]
If it was better than [4chan X + things I want] then I wouldn't have to work on it anymore.

**Comment by vendethiel** [comment]
At least you don't wake up to discover the whole fucking layout changed only to look worse (5 minor differences and a horrible font) https://github.com/Nami-Doc/wowboardhelpers/commit/b2abc477b2c8ebaae39f532573bd445528761314

**Comment by nstepien** [comment]
The grass is always greener on the other side.

**Comment by aeosynth** [comment]
i'd suggest re-evaluating your downstream. even if their work isn't the best quality, it might be good enough

@Nami-Doc you're obviously a talented coder, why isn't your wowboard script a viral hit (judging from stars / forks)? all you have to do is be better than everything else

**Comment by vendethiel** [comment]
@aeosynth  Uh - assuming you're not sarcastic, it just so happens that most of my users aren't really technical. I got around ~ 2 pages (20 posts / page) about this issue prior to my commit (and somebody called me Lord).
But really, that's the ONLY userscript there is for wow forums. I'm better than everything else, cause there's nothing else (I'm also worse than them)

Also, it's almost only used by the french community. Last time I posted it on the EN forums, it just got ignored (even though it's fully localized) and then I got banned from the french forum because "all your messages needs to be in french else we can't check them". Yes, mods there are retarded

**Comment by aeosynth** [comment]
if you're fine with your current popularity, you can ignore this post

> most of my users aren't really technical

http://eu.battle.net/wow/fr/forum/topic/6534114222?page=1

> If you have Google Chrome:
> Go here : http://is.gd/3tUnBS
> Click the " RAW " button wowboardhelpers.user.js should download
> Go to chrome :/ / extensions, drag the file , hop !
> 
> If you have Firefox:
> install GreaseMonkey
> Go https://raw.github.com/Nami-Doc/wowboardhelpers/master/wowboardhelpers.user.js

why the shortened url for chrome, unshortened url for firefox? why no greasemonkey link?
in chrome, clicking on the raw.github.com link displays a message that shit can't be installed, but the script does download anyway

compared to:

https://4chan-x.just-believe.in/

> Chrome
> Install 4chan X, that's it.
> 
> Firefox
> Install Greasemonkey. (Scriptish is not supported.)
> Install 4chan X.

4chan x does provide a greasemonkey link, it shows neither shortened nor unshortened urls, but simply linkifies the 'install' text

you don't have a gh-pages branch, just forum threads. i couldn't even find the english language one

i suppose another condition for viral success is ease of attainment

**Comment by vendethiel** [comment]
> why the shortened url for chrome, unshortened url for firefox? why no greasemonkey link?
> in chrome, clicking on the raw.github.com link displays a message that shit can't be installed, but the script does download anyway

With firefox, it just so happens that going directly on the "raw" link works. For chrome, if you go directly on the link, it refuses, but with a redirection it worked, so I put the link to the redirection.

> but simply linkifies the 'install' text

That's Wow forums. You don't have links here. Yep, it sucks (I did steal @qqueue 's autolink, though)

> why no greasemonkey link?

edited

> i couldn't even find the english language one

It's here : http://eu.battle.net/wow/en/forum/topic/6607600729#1
Dryqqn and Penances are both friends I asked to bump. I tried to post it several times and in different forums. They don't care, well, whatever (bumped anyway)

EDIT : http://eu.battle.net/wow/en/forum/topic/6609340869#1 apparently I posted it here too, ha !

**Comment by aeosynth** [comment]
> That's Wow forums. You don't have links here. Yep, it sucks

so make your own page on github. forum threads are fine, but a canonical url would help, too

**Comment by vendethiel** [comment]
I definitely should. But then I'd need to make a script to update my gh-pages branch (I don't even know how you publish that but I guess it's easy enough), I also need to pick a theme, etc.
Next time I have holidays, maybe ... (which should be around june)

**Comment by aeosynth** [comment]
your gh-pages branch doesn't need frequent updates, all it has to do is give install instructions. you could create the gh-pages branch and index.html through the github interface in 15 minutes

**Comment by vendethiel** [comment]
I need to check github's interface then :). ty

**Comment by qqueue** [comment]
Hello friends, the proverbial rumors of my death have proverbially been greatly exaggerated. I'm working on something cool, here's a sneak peak:

![screenshot - 02042014 - 10 44 22 pm](https://f.cloud.github.com/assets/1281194/2084588/9d6215e0-8e28-11e3-980a-84637a1d8e8f.png)

Active development on c4 will continue ``soon''. I'll close this bug out someday...

**Comment by aeosynth** [comment]
> data porn
> cool

well, you can't choose what you love

> I'll close this bug out someday...

as `RESOLVED`, or `WONTFIX`?

**Comment by qqueue** [comment]
Dude, definitely RESOLVED. Once I get all the hard stuff figured out, I'll just put in an option for waifu cursors or some shit--the masses of /g/ will flock to me.

Meanwhile, check out [my cool thing™](https://github.com/qqueue/fountain), while it lasts. I figure I have at least a 4 day lead on whatever moot has cooking.

**Comment by aeosynth** [comment]
kinda hard for a dead project to become more popular than a live one
